sonar.projectKey=ziriuz84_asteroidpy_1d603420-1b43-4943-86f6-ab01cd7be87b
sonar.projectName=AsteroidPy

sonar.sources=asteroidpy
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.9
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.exclusions=**/locales/**,**/*.tcss,**/__pycache__/**
